using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace eQuantic.Core.Data.Evolution;

/// <summary>
///     Writes a <see cref="ModelSnapshot" /> as the C# file that is committed with the change it explains.
///     Everything is emitted in a fixed order — entities by type, fields by member — so regenerating an unchanged
///     model produces a byte-identical file and a diff only ever shows what actually moved.
/// </summary>
public static class ModelSnapshotWriter
{
    /// <summary>Renders the snapshot as a compilable C# file.</summary>
    /// <param name="snapshot">The snapshot to write.</param>
    /// <param name="namespaceName">The namespace of the generated file.</param>
    /// <param name="typeName">The generated type's name.</param>
    public static string Write(ModelSnapshot snapshot, string namespaceName, string typeName = "DataModelSnapshot")
    {
        var text = new StringBuilder();
        text.AppendLine("// <auto-generated />");
        text.AppendLine("// The model as it stood when the last change was generated. Regenerated by the tooling;");
        text.AppendLine("// edit the model, not this file.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine("using eQuantic.Core.Data.Evolution;");
        text.AppendLine();
        text.AppendLine($"namespace {namespaceName};");
        text.AppendLine();
        text.AppendLine($"public sealed class {typeName} : IModelSnapshotFile");
        text.AppendLine("{");
        text.AppendLine("    /// <inheritdoc />");
        text.AppendLine("    public ModelSnapshot Model => new(");
        text.AppendLine($"        {Literal(snapshot.Provider)},");
        text.AppendLine("        [");

        foreach (var entity in snapshot.Entities)
        {
            WriteEntity(text, entity);
        }

        text.AppendLine("        ]);");
        text.AppendLine("}");
        return text.ToString();
    }

    private static void WriteEntity(StringBuilder text, EntitySnapshot entity)
    {
        text.AppendLine($"            new EntitySnapshot({Literal(entity.EntityType)}, {Literal(entity.Collection)},");
        text.AppendLine("                [");
        foreach (var field in entity.Fields)
        {
            text.AppendLine($"                    {Field(field)},");
        }

        text.AppendLine("                ])");
        text.AppendLine("            {");
        text.AppendLine($"                Keys = {Strings(entity.Keys)},");

        if (entity.KeyIsGenerated)
        {
            text.AppendLine("                KeyIsGenerated = true,");
        }

        if (entity.PartitionKeys.Count > 0)
        {
            text.AppendLine($"                PartitionKeys = {Strings(entity.PartitionKeys)},");
        }

        if (entity.Clustering.Count > 0)
        {
            var clustering = entity.Clustering
                .Select(order => $"new ClusteringSnapshot({Literal(order.Member)}, {Bool(order.Descending)})");
            text.AppendLine($"                Clustering = [{string.Join(", ", clustering)}],");
        }

        if (entity.ConcurrencyField is not null)
        {
            text.AppendLine($"                ConcurrencyField = {Literal(entity.ConcurrencyField)},");
        }

        if (entity.TimeToLiveSeconds is { } ttl)
        {
            text.AppendLine($"                TimeToLiveSeconds = {ttl.ToString(CultureInfo.InvariantCulture)},");
        }

        if (entity.Search.Count > 0)
        {
            var search = entity.Search
                .Select(column => $"new SearchSnapshot({Literal(column.Member)}, {Literal(column.Mode)})");
            text.AppendLine($"                Search = [{string.Join(", ", search)}],");
        }

        text.AppendLine("            },");
    }

    private static string Field(FieldSnapshot field)
    {
        var text = new StringBuilder($"new FieldSnapshot({Literal(field.Member)}, {Literal(field.Name)}, {Literal(field.StoredType)})");
        var facets = new List<string>();

        if (field.Length != 0)
        {
            facets.Add($"Length = {field.Length.ToString(CultureInfo.InvariantCulture)}");
        }

        if (field.Precision != 0)
        {
            facets.Add($"Precision = {field.Precision.ToString(CultureInfo.InvariantCulture)}");
        }

        if (field.Scale != 0)
        {
            facets.Add($"Scale = {field.Scale.ToString(CultureInfo.InvariantCulture)}");
        }

        if (field.Nullable)
        {
            facets.Add("Nullable = true");
        }

        if (field.PreviousNames.Count > 0)
        {
            facets.Add($"PreviousNames = {Strings(field.PreviousNames)}");
        }

        if (field.DefaultLiteral is { } literal)
        {
            // already a literal — it goes in as written
            facets.Add($"DefaultLiteral = {Literal(literal)}");
        }

        return facets.Count == 0 ? text.ToString() : text.Append(" { ").Append(string.Join(", ", facets)).Append(" }").ToString();
    }

    private static string Strings(IReadOnlyList<string> values) =>
        $"[{string.Join(", ", values.Select(Literal))}]";

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
