using System.Collections;
using eQuantic.Core.Data.Query;
using eQuantic.Core.Data.Relational;
using Npgsql;

namespace eQuantic.Core.Data.PostgreSql;

/// <summary>
///     PostgreSQL's SQL flavour: snake_case naming, <c>"quoted"</c> identifiers, <c>LIMIT/OFFSET</c>, identity
///     keys read back with <c>RETURNING</c>, native array columns (membership as <c>= ANY(col)</c>, atomic
///     append/remove), row-wise tuple comparisons, and scalar-keyed dictionaries as <c>jsonb</c> document
///     columns (<c>ContainsKey</c> as the <c>?</c> operator, indexer reads as <c>-&gt;&gt;</c>).
/// </summary>
public sealed class PostgreSqlDialect : SqlDialect
{
    /// <summary>Adds the PostgreSQL-specific function translations on top of the standard set.</summary>
    public PostgreSqlDialect() =>
        Functions.Map("get_Item", (column, arguments) => $"{column} ->> {arguments[0]}");

    /// <inheritdoc />
    public override string System => "postgresql";

    /// <inheritdoc />
    public override string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

    /// <inheritdoc />
    public override string GeneratedKeyDdl => "GENERATED BY DEFAULT AS IDENTITY";

    /// <inheritdoc />
    public override string InsertSql(string quotedTable, string columns, string values, string? returningKey) =>
        returningKey is null
            ? $"INSERT INTO {quotedTable} ({columns}) VALUES ({values})"
            : $"INSERT INTO {quotedTable} ({columns}) VALUES ({values}) RETURNING {returningKey}";

    /// <inheritdoc />
    public override string CollectionContains(string column, string parameter, bool key) =>
        key
            ? $"{column} ? {parameter}"
            : $"{parameter} = ANY({column})";

    /// <inheritdoc />
    /// <remarks>A scalar-keyed dictionary maps as a <c>jsonb</c> document column.</remarks>
    public override bool IsDocumentColumn(Type type)
    {
        var dictionary = type.GetInterfaces().Append(type).FirstOrDefault(candidate =>
            candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IDictionary<,>));
        return dictionary is not null && dictionary.GetGenericArguments()[0] == typeof(string);
    }

    /// <inheritdoc />
    /// <remarks>Npgsql cannot infer <c>jsonb</c> for a dictionary value; the parameter is typed explicitly.</remarks>
    public override void ConfigureParameter(System.Data.Common.DbParameter parameter, object? value)
    {
        if (value is IDictionary && parameter is Npgsql.NpgsqlParameter npgsql)
        {
            npgsql.DataTypeName = "jsonb";
        }
    }

    /// <inheritdoc />
    public override string TupleComparison(IReadOnlyList<string> columns, ComparisonOperator op, IReadOnlyList<string> parameters) =>
        $"({string.Join(", ", columns)}) {op switch
        {
            ComparisonOperator.Equal => "=",
            ComparisonOperator.NotEqual => "<>",
            ComparisonOperator.GreaterThan => ">",
            ComparisonOperator.GreaterThanOrEqual => ">=",
            ComparisonOperator.LessThan => "<",
            ComparisonOperator.LessThanOrEqual => "<=",
            _ => throw new NotSupportedException($"The operator '{op}' is not expressible."),
        }} ({string.Join(", ", parameters)})";

    /// <inheritdoc />
    public override string CollectionMutation(string column, string parameter, bool remove, bool prepend) => remove
        ? $"{column} = (SELECT COALESCE(array_agg(x), '{{}}') FROM unnest({column}) AS x WHERE x <> ALL({parameter}))"
        : prepend
            ? $"{column} = {parameter} || {column}"
            : $"{column} = {column} || {parameter}";

    /// <inheritdoc />
    public override string AlterColumnType(string quotedTable, string quotedColumn, string sqlType) =>
        $"ALTER TABLE {quotedTable} ALTER COLUMN {quotedColumn} TYPE {sqlType} USING {quotedColumn}::{sqlType}";

    /// <inheritdoc />
    public override string CreateIndexSql(string quotedName, string quotedTable, string columns, bool unique,
        eQuantic.Core.Data.Migration.IndexMethod method, string? filter)
    {
        if (method == eQuantic.Core.Data.Migration.IndexMethod.Gin)
        {
            if (unique)
            {
                throw new NotSupportedException("PostgreSQL GIN indexes cannot enforce uniqueness.");
            }

            return $"CREATE INDEX IF NOT EXISTS {quotedName} ON {quotedTable} USING GIN ({columns})"
                   + (filter is not null ? $" WHERE {filter}" : string.Empty);
        }

        return base.CreateIndexSql(quotedName, quotedTable, columns, unique, method, filter);
    }

    /// <inheritdoc />
    /// <remarks>
    ///     A GIN trigram index (<c>pg_trgm</c>): it serves <c>LIKE</c>/<c>ILIKE</c> with leading wildcards —
    ///     <c>Contains</c>/<c>EndsWith</c> stop scanning. The extension creation is idempotent and ships with
    ///     stock PostgreSQL; it does require the privilege to create extensions in the database.
    /// </remarks>
    public override IReadOnlyList<string> SearchIndexSql(string indexName, string quotedTable, string quotedColumn) =>
    [
        "CREATE EXTENSION IF NOT EXISTS pg_trgm",
        $"CREATE INDEX IF NOT EXISTS {Quote(indexName)} ON {quotedTable} USING GIN ({quotedColumn} gin_trgm_ops)",
    ];

    /// <inheritdoc />
    public override bool SupportsBulkInsert => true;

    /// <inheritdoc />
    /// <remarks>
    ///     PostgreSQL's binary <c>COPY</c> — the fastest load path the server offers: rows stream in the wire
    ///     format with no per-row statement, parse or plan. Npgsql infers each value's type from the CLR value,
    ///     which is why the engine hands over already-converted stored values.
    /// </remarks>
    public override async Task<long> BulkInsertAsync(System.Data.Common.DbConnection connection,
        System.Data.Common.DbTransaction? transaction, string quotedTable,
        IReadOnlyList<RelationalColumn> columns, IReadOnlyList<object?[]> rows, CancellationToken cancellationToken)
    {
        var target = $"{quotedTable} ({string.Join(", ", columns.Select(column => Quote(column.Name)))})";
        var npgsql = (NpgsqlConnection)connection;

        await using var writer = await npgsql.BeginBinaryImportAsync(
            $"COPY {target} FROM STDIN (FORMAT BINARY)", cancellationToken).ConfigureAwait(false);

        foreach (var row in rows)
        {
            await writer.StartRowAsync(cancellationToken).ConfigureAwait(false);
            foreach (var value in row)
            {
                if (value is null)
                {
                    await writer.WriteNullAsync(cancellationToken).ConfigureAwait(false);
                }
                else
                {
                    await writer.WriteAsync(value, cancellationToken).ConfigureAwait(false);
                }
            }
        }

        return (long)await writer.CompleteAsync(cancellationToken).ConfigureAwait(false);
    }

    /// <inheritdoc />
    public override string AddColumnSql(string quotedTable, string quotedColumn, string sqlType) =>
        $"ALTER TABLE {quotedTable} ADD COLUMN IF NOT EXISTS {quotedColumn} {sqlType}";

    /// <inheritdoc />
    public override string DropColumnSql(string quotedTable, string quotedColumn) =>
        $"ALTER TABLE {quotedTable} DROP COLUMN IF EXISTS {quotedColumn}";

    /// <inheritdoc />
    public override string SqlType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying.IsEnum)
        {
            return "integer";
        }

        // Dictionaries are documents, not arrays — checked before the IEnumerable branch.
        if (IsDocumentColumn(underlying))
        {
            return "jsonb";
        }

        if (underlying != typeof(string) && underlying != typeof(byte[]))
        {
            if (underlying.IsArray)
            {
                return SqlType(underlying.GetElementType()!) + "[]";
            }

            var element = underlying.GetInterfaces().Append(underlying)
                .FirstOrDefault(candidate => candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
                ?.GetGenericArguments()[0];
            if (element is not null)
            {
                return SqlType(element) + "[]";
            }
        }

        return underlying switch
        {
            _ when underlying == typeof(string) => "text",
            _ when underlying == typeof(Guid) => "uuid",
            _ when underlying == typeof(bool) => "boolean",
            _ when underlying == typeof(byte) || underlying == typeof(short) => "smallint",
            _ when underlying == typeof(int) => "integer",
            _ when underlying == typeof(long) => "bigint",
            _ when underlying == typeof(float) => "real",
            _ when underlying == typeof(double) => "double precision",
            _ when underlying == typeof(decimal) => "numeric",
            _ when underlying == typeof(DateTime) || underlying == typeof(DateTimeOffset) => "timestamp with time zone",
            _ when underlying == typeof(TimeSpan) => "interval",
            _ when underlying == typeof(byte[]) => "bytea",
            _ => throw new NotSupportedException($"No PostgreSQL type mapping for '{underlying.Name}'."),
        };
    }

    /// <inheritdoc />
    public override object? BindValue(object? value) => value switch
    {
        // timestamptz demands a UTC kind; an Unspecified value is taken as UTC (matching the storage semantics).
        DateTime { Kind: DateTimeKind.Unspecified } dateTime => DateTime.SpecifyKind(dateTime, DateTimeKind.Utc),
        Enum enumValue => Convert.ToInt32(enumValue),
        _ => value,
    };
}
