using System.Collections;
using eQuantic.Core.Data.Query;
using eQuantic.Core.Data.Relational;

namespace eQuantic.Core.Data.PostgreSql;

/// <summary>
///     PostgreSQL's SQL flavour: snake_case naming, <c>"quoted"</c> identifiers, <c>LIMIT/OFFSET</c>, identity
///     keys read back with <c>RETURNING</c>, native array columns (membership as <c>= ANY(col)</c>, atomic
///     append/remove) and row-wise tuple comparisons.
/// </summary>
public sealed class PostgreSqlDialect : SqlDialect
{
    /// <inheritdoc />
    public override string System => "postgresql";

    /// <inheritdoc />
    public override string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

    /// <inheritdoc />
    public override string GeneratedKeyDdl => "GENERATED BY DEFAULT AS IDENTITY";

    /// <inheritdoc />
    public override string? InsertReturningClause(string keyColumn) => $"RETURNING {keyColumn}";

    /// <inheritdoc />
    public override string CollectionContains(string column, string parameter, bool key) =>
        key
            ? throw new NotSupportedException("Map-key membership needs a jsonb column, which the model does not declare yet.")
            : $"{parameter} = ANY({column})";

    /// <inheritdoc />
    public override string TupleComparison(IReadOnlyList<string> columns, ComparisonOperator op, IReadOnlyList<string> parameters) =>
        $"({string.Join(", ", columns)}) {op switch
        {
            ComparisonOperator.Equal => "=",
            ComparisonOperator.NotEqual => "<>",
            ComparisonOperator.GreaterThan => ">",
            ComparisonOperator.GreaterThanOrEqual => ">=",
            ComparisonOperator.LessThan => "<",
            ComparisonOperator.LessThanOrEqual => "<=",
            _ => throw new NotSupportedException($"The operator '{op}' is not expressible."),
        }} ({string.Join(", ", parameters)})";

    /// <inheritdoc />
    public override string CollectionMutation(string column, string parameter, bool remove, bool prepend) => remove
        ? $"{column} = (SELECT COALESCE(array_agg(x), '{{}}') FROM unnest({column}) AS x WHERE x <> ALL({parameter}))"
        : prepend
            ? $"{column} = {parameter} || {column}"
            : $"{column} = {column} || {parameter}";

    /// <inheritdoc />
    public override string AlterColumnType(string quotedTable, string quotedColumn, string sqlType) =>
        $"ALTER TABLE {quotedTable} ALTER COLUMN {quotedColumn} TYPE {sqlType} USING {quotedColumn}::{sqlType}";

    /// <inheritdoc />
    public override string SqlType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying.IsEnum)
        {
            return "integer";
        }

        if (underlying != typeof(string) && underlying != typeof(byte[]))
        {
            if (underlying.IsArray)
            {
                return SqlType(underlying.GetElementType()!) + "[]";
            }

            var element = underlying.GetInterfaces().Append(underlying)
                .FirstOrDefault(candidate => candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
                ?.GetGenericArguments()[0];
            if (element is not null)
            {
                return SqlType(element) + "[]";
            }
        }

        return underlying switch
        {
            _ when underlying == typeof(string) => "text",
            _ when underlying == typeof(Guid) => "uuid",
            _ when underlying == typeof(bool) => "boolean",
            _ when underlying == typeof(byte) || underlying == typeof(short) => "smallint",
            _ when underlying == typeof(int) => "integer",
            _ when underlying == typeof(long) => "bigint",
            _ when underlying == typeof(float) => "real",
            _ when underlying == typeof(double) => "double precision",
            _ when underlying == typeof(decimal) => "numeric",
            _ when underlying == typeof(DateTime) || underlying == typeof(DateTimeOffset) => "timestamp with time zone",
            _ when underlying == typeof(TimeSpan) => "interval",
            _ when underlying == typeof(byte[]) => "bytea",
            _ => throw new NotSupportedException($"No PostgreSQL type mapping for '{underlying.Name}'."),
        };
    }

    /// <inheritdoc />
    public override object? BindValue(object? value) => value switch
    {
        // timestamptz demands a UTC kind; an Unspecified value is taken as UTC (matching the storage semantics).
        DateTime { Kind: DateTimeKind.Unspecified } dateTime => DateTime.SpecifyKind(dateTime, DateTimeKind.Utc),
        Enum enumValue => Convert.ToInt32(enumValue),
        _ => value,
    };
}
