using System.Text;
using eQuantic.Core.Data.Query;

namespace eQuantic.Core.Data.Relational;

/// <summary>
///     A database's SQL flavour: identifier quoting, naming conventions, paging syntax, type names for DDL, and
///     the rendering of the constructs that differ between engines (collection membership, tuple comparisons,
///     generated-key retrieval). The shared relational engine renders everything else; a provider package is this
///     class plus a driver.
/// </summary>
public abstract class SqlDialect
{
    /// <summary>The OpenTelemetry <c>db.system</c> value (e.g. <c>postgresql</c>, <c>mysql</c>, <c>mssql</c>).</summary>
    public abstract string System { get; }

    /// <summary>Quotes an identifier (table or column name).</summary>
    public abstract string Quote(string identifier);

    /// <summary>Applies the naming convention to a member name to produce its column name (snake_case by default).</summary>
    public virtual string ColumnName(string memberName) => SnakeCase(memberName);

    /// <summary>Applies the naming convention to an entity name to produce its table name (snake_case by default).</summary>
    public virtual string TableName(string entityName) => SnakeCase(entityName);

    /// <summary>The SQL fragment limiting a query to the bound row count after the bound offset (appended after ORDER BY).</summary>
    public virtual string LimitClause(string limitParameter, string? offsetParameter) =>
        offsetParameter is null ? $"LIMIT {limitParameter}" : $"LIMIT {limitParameter} OFFSET {offsetParameter}";

    /// <summary>The DDL type for a CLR type (used by <c>CREATE TABLE</c> migrations).</summary>
    public abstract string SqlType(Type type);

    /// <summary>The DDL column suffix declaring a database-generated key (e.g. <c>GENERATED BY DEFAULT AS IDENTITY</c>).</summary>
    public abstract string GeneratedKeyDdl { get; }

    /// <summary>
    ///     The clause an insert uses to read back a generated key, or <c>null</c> when the dialect cannot
    ///     (the provider then falls back to its own mechanism).
    /// </summary>
    public virtual string? InsertReturningClause(string keyColumn) => null;

    /// <summary>
    ///     Renders a collection-membership test (<c>member CONTAINS value</c> / <c>CONTAINS KEY</c>) for stores
    ///     with native collection columns; the base dialect cannot express it (the clause degrades to residual).
    /// </summary>
    /// <param name="column">The quoted column.</param>
    /// <param name="parameter">The bound value's parameter marker.</param>
    /// <param name="key">Whether the test targets a map key.</param>
    public virtual string CollectionContains(string column, string parameter, bool key) =>
        throw new NotSupportedException($"{GetType().Name} has no native collection membership; the clause runs client-side.");

    /// <summary>Renders a row-wise tuple comparison; the base dialect cannot express it.</summary>
    /// <param name="columns">The quoted columns.</param>
    /// <param name="op">The comparison operator.</param>
    /// <param name="parameters">The bound values' parameter markers.</param>
    public virtual string TupleComparison(IReadOnlyList<string> columns, ComparisonOperator op, IReadOnlyList<string> parameters) =>
        throw new NotSupportedException($"{GetType().Name} has no native tuple comparison; the clause runs client-side.");

    /// <summary>Renders a collection-mutating SET fragment (<c>col = col + items</c>), for stores with collection columns.</summary>
    /// <param name="column">The quoted column.</param>
    /// <param name="parameter">The bound items' parameter marker.</param>
    /// <param name="remove">Whether the items are removed instead of added.</param>
    /// <param name="prepend">Whether added items go at the front.</param>
    public virtual string CollectionMutation(string column, string parameter, bool remove, bool prepend) =>
        throw new NotSupportedException($"{GetType().Name} has no native collection columns; load the rows and Modify them instead.");

    /// <summary>The DDL altering a column's type (a dialect may need a cast clause).</summary>
    public virtual string AlterColumnType(string quotedTable, string quotedColumn, string sqlType) =>
        $"ALTER TABLE {quotedTable} ALTER COLUMN {quotedColumn} TYPE {sqlType}";

    /// <summary>Converts a value before binding (a dialect may need CLR-side coercion, e.g. arrays); identity by default.</summary>
    public virtual object? BindValue(object? value) => value;

    private static string SnakeCase(string name)
    {
        var builder = new StringBuilder(name.Length + 4);
        for (var index = 0; index < name.Length; index++)
        {
            var character = name[index];
            if (char.IsUpper(character))
            {
                if (index > 0 && (char.IsLower(name[index - 1]) || (index + 1 < name.Length && char.IsLower(name[index + 1]))))
                {
                    builder.Append('_');
                }

                builder.Append(char.ToLowerInvariant(character));
            }
            else
            {
                builder.Append(character);
            }
        }

        return builder.ToString();
    }
}
