using System.Text;
using eQuantic.Core.Data.Query;

namespace eQuantic.Core.Data.Relational;

/// <summary>
///     A database's SQL flavour: identifier quoting, naming conventions, paging syntax, type names for DDL, and
///     the rendering of the constructs that differ between engines (collection membership, tuple comparisons,
///     generated-key retrieval). The shared relational engine renders everything else; a provider package is this
///     class plus a driver.
/// </summary>
public abstract class SqlDialect
{
    /// <summary>Initializes the dialect with the standard function translations.</summary>
    protected SqlDialect() =>
        Functions
            .Map("ToLower", (column, _) => $"LOWER({column})")
            .Map("ToUpper", (column, _) => $"UPPER({column})")
            .Map("Trim", (column, _) => $"TRIM({column})")
            .Map("Like", (column, arguments) => $"{column} LIKE {arguments[0]}")
            .Map("IsNullOrEmpty", (column, _) => $"({column} IS NULL OR {column} = '')")
            .Map("Year", (column, _) => $"EXTRACT(YEAR FROM {column})")
            .Map("Month", (column, _) => $"EXTRACT(MONTH FROM {column})")
            .Map("Day", (column, _) => $"EXTRACT(DAY FROM {column})");

    /// <summary>The OpenTelemetry <c>db.system</c> value (e.g. <c>postgresql</c>, <c>mysql</c>, <c>mssql</c>).</summary>
    public abstract string System { get; }

    /// <summary>The function translations this dialect knows — extend it with <see cref="SqlFunctionRegistry.Map" />.</summary>
    public SqlFunctionRegistry Functions { get; } = new();

    /// <summary>Quotes an identifier (table or column name).</summary>
    public abstract string Quote(string identifier);

    /// <summary>Applies the naming convention to a member name to produce its column name (snake_case by default).</summary>
    public virtual string ColumnName(string memberName) => SnakeCase(memberName);

    /// <summary>Applies the naming convention to an entity name to produce its table name (snake_case by default).</summary>
    public virtual string TableName(string entityName) => SnakeCase(entityName);

    /// <summary>The SQL fragment limiting a query to the bound row count after the bound offset (appended after ORDER BY).</summary>
    public virtual string LimitClause(string limitParameter, string? offsetParameter) =>
        offsetParameter is null ? $"LIMIT {limitParameter}" : $"LIMIT {limitParameter} OFFSET {offsetParameter}";

    /// <summary>Whether a limited query must carry an ORDER BY (SQL Server's <c>OFFSET/FETCH</c>); the key is used when unsorted.</summary>
    public virtual bool RequiresOrderByForLimit => false;

    /// <summary>The literal for an always-false predicate (an empty <c>IN</c>); some dialects have no <c>FALSE</c>.</summary>
    public virtual string FalseLiteral => "FALSE";

    /// <summary>The DDL type for a CLR type (used by <c>CREATE TABLE</c> migrations).</summary>
    public abstract string SqlType(Type type);

    /// <summary>The DDL column suffix declaring a database-generated key (e.g. <c>GENERATED BY DEFAULT AS IDENTITY</c>).</summary>
    public abstract string GeneratedKeyDdl { get; }

    /// <summary>
    ///     Builds an INSERT, reading the generated key back when <paramref name="returningKey" /> is supplied
    ///     (<c>RETURNING</c> / <c>OUTPUT INSERTED</c>). The base dialect cannot read keys back — declare a
    ///     client-generated key, or use a dialect that can.
    /// </summary>
    /// <param name="quotedTable">The quoted table.</param>
    /// <param name="columns">The quoted column list.</param>
    /// <param name="values">The bound value list.</param>
    /// <param name="returningKey">The quoted generated-key column to read back, or <c>null</c>.</param>
    public virtual string InsertSql(string quotedTable, string columns, string values, string? returningKey) =>
        returningKey is null
            ? $"INSERT INTO {quotedTable} ({columns}) VALUES ({values})"
            : throw new NotSupportedException(
                $"{GetType().Name} cannot read a generated key back from an insert; declare a client-generated key instead.");

    /// <summary>Builds an idempotent CREATE TABLE statement.</summary>
    /// <param name="quotedTable">The quoted table.</param>
    /// <param name="columnsDdl">The column declaration list.</param>
    public virtual string CreateTableSql(string quotedTable, string columnsDdl) =>
        $"CREATE TABLE IF NOT EXISTS {quotedTable} ({columnsDdl})";

    /// <summary>Builds a CREATE INDEX statement (idempotent where the dialect supports it; migration history guards re-runs otherwise).</summary>
    /// <param name="quotedName">The quoted index name.</param>
    /// <param name="quotedTable">The quoted table.</param>
    /// <param name="columns">The quoted key column list (with directions).</param>
    /// <param name="unique">Whether the index enforces uniqueness.</param>
    public virtual string CreateIndexSql(string quotedName, string quotedTable, string columns, bool unique) =>
        $"CREATE {(unique ? "UNIQUE " : string.Empty)}INDEX IF NOT EXISTS {quotedName} ON {quotedTable} ({columns})";

    /// <summary>
    ///     Renders a collection-membership test (<c>member CONTAINS value</c> / <c>CONTAINS KEY</c>) for stores
    ///     with native collection columns; the base dialect cannot express it (the clause degrades to residual).
    /// </summary>
    /// <param name="column">The quoted column.</param>
    /// <param name="parameter">The bound value's parameter marker.</param>
    /// <param name="key">Whether the test targets a map key.</param>
    public virtual string CollectionContains(string column, string parameter, bool key) =>
        throw new NotSupportedException($"{GetType().Name} has no native collection membership; the clause runs client-side.");

    /// <summary>Renders a row-wise tuple comparison; the base dialect cannot express it.</summary>
    /// <param name="columns">The quoted columns.</param>
    /// <param name="op">The comparison operator.</param>
    /// <param name="parameters">The bound values' parameter markers.</param>
    public virtual string TupleComparison(IReadOnlyList<string> columns, ComparisonOperator op, IReadOnlyList<string> parameters) =>
        throw new NotSupportedException($"{GetType().Name} has no native tuple comparison; the clause runs client-side.");

    /// <summary>Renders a collection-mutating SET fragment (<c>col = col + items</c>), for stores with collection columns.</summary>
    /// <param name="column">The quoted column.</param>
    /// <param name="parameter">The bound items' parameter marker.</param>
    /// <param name="remove">Whether the items are removed instead of added.</param>
    /// <param name="prepend">Whether added items go at the front.</param>
    public virtual string CollectionMutation(string column, string parameter, bool remove, bool prepend) =>
        throw new NotSupportedException($"{GetType().Name} has no native collection columns; load the rows and Modify them instead.");

    /// <summary>The DDL altering a column's type (a dialect may need a cast clause).</summary>
    public virtual string AlterColumnType(string quotedTable, string quotedColumn, string sqlType) =>
        $"ALTER TABLE {quotedTable} ALTER COLUMN {quotedColumn} TYPE {sqlType}";

    /// <summary>Converts a value before binding (a dialect may need CLR-side coercion, e.g. arrays); identity by default.</summary>
    public virtual object? BindValue(object? value) => value;

    private static string SnakeCase(string name)
    {
        var builder = new StringBuilder(name.Length + 4);
        for (var index = 0; index < name.Length; index++)
        {
            var character = name[index];
            if (char.IsUpper(character))
            {
                if (index > 0 && (char.IsLower(name[index - 1]) || (index + 1 < name.Length && char.IsLower(name[index + 1]))))
                {
                    builder.Append('_');
                }

                builder.Append(char.ToLowerInvariant(character));
            }
            else
            {
                builder.Append(character);
            }
        }

        return builder.ToString();
    }
}
